server:
 port: 8088

logging:
 config: classpath:config/logback-spring.xml

spring:
 datasource:
  username: root
  password: k200
  url: jdbc:mysql://localhost:3306/mybatis?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
  driver-class-name: com.mysql.jdbc.Driver

mybatis:
 mapper-locations: classpath:mapper/*.xml
 type-aliases-package: com.example.web.model